model:
  base_learning_rate: 5e-4
  target: src.canonicalvq.models.CanonicalVQ
  params:
    feat_dim: 256
    n_embed: 5000
    num_groups: 64
    mode: 0 # corr
    train_unfold: False
    no_fold: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 0
    train:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'train'
        categories: ['airplane']
        tr_sample_size: 2048
        te_sample_size: 2048
    validation:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['airplane']
        tr_sample_size: 2048
        te_sample_size: 2048
    test:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['airplane']
        tr_sample_size: 2048
        te_sample_size: 2048