model:
  base_learning_rate: 5e-4
  target: src.canonicalvq.models.CanonicalVQ
  params:
    feat_dim: 256
    n_embed: 5000
    num_groups: 128
    mode: 2 # FT
    codebook_size: 50
    # ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/airplane_2022-01-31T07-56-10_delete/testtube/version_0/checkpoints/epoch=19-step=2359.ckpt
    ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/airplane_2022-02-06T20-04-20_stage3_Decay/testtube/version_0/checkpoints/epoch=3999-step=119999.ckpt
    ignore_keys: ['VQ']
    train_unfold: False
    no_fold: False


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 0
    train:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'train'
        categories: ['airplane']
        tr_sample_size: 2048
        te_sample_size: 2048
    validation:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['airplane']
        tr_sample_size: 2048
        te_sample_size: 2048
    test:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['airplane']
        tr_sample_size: 2048
        te_sample_size: 2048