model:
  base_learning_rate: 5e-4
  target: src.canonicalvq.models.CanonicalVQ
  params:
    feat_dim: 256
    n_embed: 5000
    num_groups: 128
    codebook_size: 50
    mode: 2 # FT
    ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/car_2022-01-25T16-31-51_stage1_128/testtube/version_0/checkpoints/epoch=499-step=9999.ckpt
    # ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/car_2022-01-25T16-31-51_stage1_128/checkpoints/epoch=169-step=3399.ckpt
    ignore_keys: ['VQ']
    train_unfold: False
    no_fold: False


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 0
    train:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'train'
        categories: ['car']
        tr_sample_size: 2048
        te_sample_size: 2048
    validation:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['car']
        tr_sample_size: 2048
        te_sample_size: 2048
    test:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['car']
        tr_sample_size: 2048
        te_sample_size: 2048