model:
  base_learning_rate: 5e-4
  target: src.canonicalvq.models.CanonicalVQ
  params:
    feat_dim: 256
    n_embed: 5000
    num_groups: 128
    codebook_size: 50
    mode: 3 # Transformer
    ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/chair_2022-02-01T18-20-30_cb50/testtube/version_0/checkpoints/epoch=2649-step=129849.ckpt
    # ignore_keys: ['VQ']
    train_unfold: False
    no_fold: False
    # ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/chair_2022-01-16T13-14-51_chair_ft_VQ_5000/testtube/version_0/checkpoints/epoch=1219-step=89059.ckpt


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 0
    train:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'train'
        categories: ['chair']
        tr_sample_size: 2048
        te_sample_size: 2048
    validation:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['chair']
        tr_sample_size: 2048
        te_sample_size: 2048
    test:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['chair']
        tr_sample_size: 2048
        te_sample_size: 2048