model:
  base_learning_rate: 5e-4
  target: src.canonicalvq.models.CanonicalVQ
  params:
    feat_dim: 256
    n_embed: 5000
    num_groups: 128
    mode: 1 # PG
    # ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/chair_2022-01-18T10-40-41_base/testtube/version_0/checkpoints/epoch=1109-step=81029.ckpt
    ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/chair_2022-01-20T07-29-26_SPGAN_noTanh/testtube/version_0/checkpoints/epoch=3999-step=147999.ckpt
    ignore_keys: ['PG']
    train_unfold: False
    no_fold: False
    pg_from_standard: False
    # ckpt_path: /home/vslab2018/3d/CanonicalVAE/logs/restore_chair.ckpt


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 0
    train:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'train'
        categories: ['chair']
        tr_sample_size: 2048
        te_sample_size: 2048
    validation:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['chair']
        tr_sample_size: 2048
        te_sample_size: 2048
    test:
      target: src.data.core.ShapeNet15kPointClouds
      params:
        split: 'val'
        categories: ['chair']
        tr_sample_size: 2048
        te_sample_size: 2048