method: canonicalvq
data:
  dataset: ShapeNet
  shapenet_data_dir: "/home/vslab2018/data/ShapeNetCore.v2.PC15k/"
  cates: ['airplane']
  batch_size: 32
  tr_max_sample_points: 2500
  te_max_sample_points: 2025
  dataset_scale: 1.
  normalize_per_shape: false
  normalize_std_per_axis: false
  standardize_per_shape: true #####
  no_normalize: True #####
model:
  feat_dim: 128
  encoder: DGCNN
  stage1:
    decoder_u: FOLDINGNET
    decoder_f: SPGAN
    decoder_u_use_local: False
    decoder_f_use_local: True
  stage2:
    num_groups: 256
    vocab_size: 5000
    discriminator: false
    perceptual: false
training:
  mode: vq
  out_dir:  out/default
  vq_path: false
  print_every: 10
  visualize_every: 3000000
  checkpoint_every: 200
  min_val_epoch: 2500000000000
  validate_every: 1000 # 500
  backup_every: 5000
  model_selection_metric: CD
  model_selection_mode: minimize
  load_from: false
evaluate:
  generation: false
  reconstruction: true
visdom:
  env: main
  port: 5000
  


